version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet build src/ironbar.sln
      - run: dotnet test src/ironbar.sln --no-build
